<a href="https://colab.research.google.com/github/2023AC05202/pytorch_tutorial_1/blob/develop/2_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

# LIST

In [ ]:
mylist = [[1,2,3,4],[6,5,4,3]]
mylist

[[1, 2, 3, 4], [6, 5, 4, 3]]

# NUMPY ARRAY

In [ ]:
npArray = np.random.rand(3, 4)
npArray

array([[0.21986718, 0.79684483, 0.2895851 , 0.68837739],
       [0.99110984, 0.51692277, 0.74414841, 0.12446898],
       [0.66121312, 0.13436353, 0.27378419, 0.62693127]])

In [ ]:
npArray.dtype

dtype('float64')

# TENSONRS

In [ ]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 0.2083,  0.4396, -0.3174,  1.4472],
        [ 0.8144,  2.1649,  1.4985,  1.5370],
        [-0.1852,  1.5906, -0.3017,  0.8583]])

In [ ]:
tensor_3d = torch.randn(2,3,4)
tensor_3d

tensor([[[ 0.2916,  0.8399,  1.0276,  0.0790],
         [-0.5209, -1.2732,  0.3584,  0.3490],
         [ 1.8924,  1.7206,  1.2286, -0.8496]],

        [[-0.2040,  0.5259, -0.1168,  1.3046],
         [-0.2549, -0.3199,  0.1885,  0.6298],
         [ 0.1271, -1.4932,  1.6738, -0.2348]]])

In [ ]:
tensor_3d.dtype

torch.float32

In [ ]:
mytensor = torch.tensor(npArray)
mytensor

tensor([[0.2199, 0.7968, 0.2896, 0.6884],
        [0.9911, 0.5169, 0.7441, 0.1245],
        [0.6612, 0.1344, 0.2738, 0.6269]], dtype=torch.float64)