<a href="https://colab.research.google.com/github/2023AC05202/pytorch_tutorial_1/blob/develop/3_Tensor_ops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# reshape and view
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
#reshape if we don't know the number of records
my_torch2 = torch.arange(10)
my_torch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_torch2 = my_torch2.reshape(2,-1)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
#View
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_torch3 = my_torch3.view(2,5)
my_torch3

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
# reshape and view will update the origonal
my_torch4 = torch.arange(10)
my_torch4

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_torch5 = my_torch4.reshape(2,5)
my_torch5

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
my_torch4[1] = 4141
my_torch4

tensor([   0, 4141,    2,    3,    4,    5,    6,    7,    8,    9])

In [ ]:
my_torch5

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [ ]:
#Slice
my_torch7 = torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#Grab a specific item
my_torch7[6]

tensor(6)

In [ ]:
# Grab a slice
my_torch8 = my_torch7.reshape(5,2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [ ]:
my_torch8[:,1]

tensor([1, 3, 5, 7, 9])

In [ ]:
#return column
my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])