<a href="https://colab.research.google.com/github/2023AC05202/pytorch_tutorial_1/blob/develop/4_Tensor_Maths.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [3]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [4]:
#Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [6]:
#Long hand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [7]:
#Subtraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [8]:
#Subtraction
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [9]:
#Multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [10]:
#Multiplication function
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [11]:
#Division
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [12]:
#Division Function
torch.div(tensor_b, tensor_a)


tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [13]:
#Remainder
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [14]:
#Remainder function
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [15]:
#Exponential
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [17]:
tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 12])

In [18]:
tensor_a

tensor([ 6,  8, 10, 12])